= Rapport d’avancement du groupe “1.1”
PACT groupe 1.1
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== PACT 1.1

=== Membres du groupe

* Audit Anna 
* Roussy Erwann
* Danet Hugo
* Ben Friha Adame
* Mazars Mikael
* Hadida Jody
* Sersouri Al Mahdi

=== Tuteur

* Le Feuvre Jean

=== Encadrant génie logiciel

* Moissinac Jean-Claude

== Résumé du sujet choisi en français (PAN1)

La CureBox est un pilulier intelligent. Elle s’adresse principalement aux personnes âgées dont la condition nécessite la prise d'un traitement quotidien, mais qui ne peuvent pas être autonome pour prendre leur traitement (risque d’oubli, ou même simple problème moteur pour ouvrir un pilulier classique). La boîte peut être programmée à l'aide d’une application mobile par la famille ou encore un médecin. Une fois programmée, la boîte délivre les médicaments souhaités aux heures prévues dans la quantité indiquée. Elle est également équipée d’un système d’alarme en cas de non-prise du médicament. La CureBox permet à des personnes âgées d'être plus autonomes, d'avoir moins recours à l’aide d’une infirmière ou d’une aide soignante afin de retarder un éventuel départ en maison de retraite. L’usager peut ainsi rester dans un environnement familier plus chaleureux.

== English Summary (PAN1)

The CureBox is an intelligent pillbox. Its principal target is the elderly whose condition requires to take a daily treatment, but who aren’t fully self-sufficient when it comes to taking their treatment (for instance risk that they might forget, or even motor impairment making it challenging to open a regular pillbox). The CureBox can be programmed through an app by a family member or a doctor. Once programmed it will deliver the medicament at the planned time in the required quantities. The CureBox is also equipped with a alarm system if the medicine is not taken. The CureBox will enable elderly to be more self-sufficient, they will not need as much help from a nurse and this can allow to delay a departure in a nursing home. The user can as a consequence remain in an environment that is more familiar and warm.

// *Notes concenant le rapport*

// Les différentes pages du document sont rédigées en utilisant le langage AsciiDoc. Le squelette de rapport contient des exemples avec entre autre:

// * des images, * des liens, * des équations.

// La structure du rapport (parties, sections et la relation avec les differents fichiers) se trouve dans le fichier courant.

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

// include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

//include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

//<<<

// [bibliography]
// == Bibliographie (PAN1+)

// include::References.adoc[Bibliographie]

// <<<

// == Annexes

// include::annexes/modifications.adoc[Modifications (PAN2+)]

// include::annexes/avancement.adoc[Avancement des modules]

// include::annexes/moduleX.adoc[Avancement module X]

// include::annexes/moduleY.adoc[Avancement module Y]
