=== Scénarios d’usage
//Mettre ici le scénario d’usage que vous avez construit lors des séances
//encadrées par les experts SES. Vous pouvez mettre un scénario amélioré
//(et non celui noté) si vous jugez votre scénario insuffisant pour faire
//comprendre au jury PACT les différentes étapes d’utilisation de votre
//produit/service ou si vous avez changé d’idées entre temps.

Brigitte, 70 ans, à autonomie réduite, est atteinte d’une maladie nécessitant une prise régulière de plusieurs médicaments. Elle doit prendre un premier médicament avant chaque repas, puis un deuxième médicament une heure après le premier. Elle ne doit rien oublier, et doit impérativement respecter ce délai d’une heure. Sa famille souhaite l’aider à suivre son traitement, mais ne peut pas venir quotidiennement vérifier son bon déroulement.

La CureBox permet à Brigitte d’être plus autonome dans sa prise de médicaments, et ainsi de rassurer son entourage. Si nécessaire, elle permet également d’avoir un suivi de traitement exploitable par son médecin. Il s’agit d’une boîte de distribution automatique et intelligente de médicaments, jumelée à une application Android permettant de la programmer. La CureBox doit tout d’abord être branchée sur une prise secteur et connectée en Wi-fi à l’application. Ensuite, grâce à l’application, un proche de Brigitte ou son médecin peut programmer l’emploi du temps de la CureBox, les horaires de prise de médicaments, ainsi que la quantité à délivrer. L’application disposera également d’une base de données interne, qui permettra, en scannant le QR code d’un médicament, d’avoir accès à des informations sur ce médicament (poids des pilules notamment), et en outre, de programmer automatiquement l’emploi du temps en fonction de la posologie. On remplit ensuite un des dix compartiments (un compartiment contient plusieurs pilules/gélules d’un même médicament). Après confirmation , la CureBox est initialisée et prête à l’emploi.

Par exemple, pour un médicament qui doit être pris à 14h, voici ce qu’il se passe :
* 13h50 : Dix minutes avant le moment prévu pour la prise de médicaments, la CureBox se met en marche et prépare la pilule de 14h.
* 14h : la pilule sort et un signal lumineux se déclenche (clignotement régulier de LEDs) pour avertir Brigitte de l’arrivée du médicament dans le réceptacle.
* 14h01 : un signal vocal se déclenche. Tant que les pilules ne sont pas récupérées, 	les signaux sont répétés de façon régulière en s’intensifiant.
* 14h30 : si la prise de médicaments n’a toujours pas été effectuée, CureBox 		  avertit par SMS Brigitte, si elle a un téléphone.
Au bout de x prises oubliées (personnalisable selon la volonté de la famille et du médecin), un SMS d’avertissement est envoyé à la famille.

L’utilisation de la CureBox par Brigitte est donc ergonomique, elle doit seulement saisir
les pilules aux bons horaires, aucune autre action n’est demandée auprès de cet utilisateur. Sinon, la CureBox vérifie l’absence des pilules à l’aide d’un capteur de pression et la journée continue normalement. S’il est prévu qu’un deuxième médicament vienne exactement une heure après la première prise, il ne sera livré qu’une heure après le ramassage du premier médicament. À terme il sera également possible de rajouter d’autres fonctionnalités à la CureBox, comme par exemple un bracelet connecté pour avertir Brigitte, ou l’ajout de plusieurs utilisateurs sur la même boîte.

Le dimensionnement de la CureBox fait l’objet d’un soin tout particulier : en effet, il est essentiel que la CureBox soit de taille et de poids permettant son transport sans difficulté, mais elle devra tout de même être assez stable pour l’empêcher de se renverser. Quelques conditions de placement s’imposent : la CureBox doit être à proximité d’une prise ainsi que d’un robinet pour prendre les médicaments, et l’humidité ne doit pas altérer la conservation des médicaments.

Détails techniques :
Le principe de stockage et récupération des médicaments est sujet à changements. Nous ne sommes pas encore sûrs de la meilleure approche à adopter.

//==== XX

//Nulla. Curabitur aliquet leo ac massa. Praesent posuere lectus vitae
//odio. Donec imperdiet urna vel ante. In semper accumsan diam. Vestibulum
//porta justo. Suspendisse egestas commodo eros.

//Suspendisse tincidunt mi vel metus. Vivamus non urna in nisi gravida
//congue. Aenean semper orci a eros. Praesent dictum. Maecenas pharetra
//odio ut dui. Pellentesque.

//==== YY

//Ac mauris.

//Duis velit magna, scelerisque vitae, varius ut, aliquam vel, justo.
//Proin ac augue. Nullam auctor lectus vitae arcu. Vestibulum porta justo
//placerat purus. Ut sem nunc, vestibulum nec, sodales vitae, vehicula
//eget, ipsum. Sed nec tortor. Aenean malesuada. Nunc convallis, massa eu
//vestibulum commodo, quam mauris interdum arcu, at pellentesque.
